Django/schoolapp/schoolapp/urls.py
from django.contrib import admin
from django.urls import path
from students import views

admin.site.site_header = "Admin Dashboard"
admin.site.site_title = "Admin Dashboard"
admin.site.index_title = "School Administration"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.registration),
    path('show/',views.show),
    path('success',views.success),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),
]

Django/schoolapp/students/models.py
from django.db import models

class RegistrationForm(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    roll_no = models.IntegerField(unique = True, null=True)
    father_name = models.CharField(max_length=50)
    mother_name = models.CharField(max_length=50)
    address = models.TextField()
    registration_date = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now = True)
    
    
    def __str__(self):
        self.name = self.first_name + " " + self.last_name 
        return self.name

    class Meta:
        db_table = "student"

Django/schoolapp/students/forms.py
from django import forms
from students.models import RegistrationForm

class Registration(forms.ModelForm):
    class Meta:
        model = RegistrationForm
        fields = "__all__"

Django/schoolapp/students/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from students.models import RegistrationForm
from students.forms import Registration

def front(request):
    return render(request,"front.html")

def registration(request):
    if request.method == "POST":
        form = Registration(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/success')   
            except:
                pass
    else:
        form = Registration()
    return render(request,'index.html',{'form':form})

def success(request):
    return render(request,'success.html')

def show(request):  
    showdata = RegistrationForm.objects.all()  
    return render(request,'show.html',{'showdata':showdata})

def edit(request, id):  
    student = RegistrationForm.objects.get(id=id)  
    form = Registration(request.POST, instance = student)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")
    return render(request,'edit.html', {'student':student})

def update(request, id):  
    student = RegistrationForm.objects.get(id=id)  
    form = Registration(request.POST, instance = student)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'student': student})

def destroy(request, id):  
    student = RegistrationForm.objects.get(id=id)  
    student.delete()  
    return redirect("/show")    
    
    
    #return redirect('/')

Django/schoolapp/students/templates/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <style>
        .button {
            border: none;
            padding: 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }

        .button4 {
            border-radius: 12px;
        }
    </style>
</head>

<body>
    <form align="center" method="POST" class="post-form" action="/update/{{student.id}}">
        {% csrf_token %}
        <div class="container" style="background:lightgrey; height:100%;">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Update Details</h3>
                </div>
            </div>
            <div class="form-group row">
                <br>
                {% comment %} <label class="col-sm-2 col-form-label">First Name:</label>   {% endcomment %}
                <div class="col-sm-4">
                    First Name:<input type="text" name="first_name" id="id_first_name" required maxlength="30"
                        value="{{ student.first_name }}" />
                </div>
            </div>
            <div class="form-group row">
                <br>  
                {% comment %} <label class="col-sm-2 col-form-label">Last Name:</label>   {% endcomment %}
                <div class="col-sm-4">
                    Last Name:<input type="text" name="last_name" id="id_last_name" required maxlength="30"
                        value="{{ student.last_name }}" />
                </div>
            </div>
            <div class="form-group row">
                <br>
                {% comment %} <label class="col-sm-2 col-form-label">Age:</label>   {% endcomment %}
                <div class="col-sm-4">
                    Age:<input type="number" name="age" id="id_age" value="{{ student.age }}" />
                </div>
            </div>
            <div class="form-group row">
                <br>
                {% comment %} <label class="col-sm-2 col-form-label">Gender:</label>   {% endcomment %}
                <div class="col-sm-4">
                    Gender:
                    <input type="radio" id="id_male" name="gender" value="{{ student.gender }}" />
                    <label for="male">Male</label>
                    <input type="radio" id="id_female" name="gender" value="{{ student.gender }}" />
                    <label for="female">Female</label><br>
                </div>
            </div>
            <div class="form-group row">
                <br>
                {% comment %} <label class="col-sm-2 col-form-label">Roll No:</label>   {% endcomment %}
                <div class="col-sm-4">
                    Roll No:<input type="number" name="roll_no" id="id_roll_no" value="{{ student.roll_no }}" />
                </div>
            </div>

            <div class="form-group row">
                <br>
                {% comment %} <label class="col-sm-2 col-form-label">Father Name:</label>   {% endcomment %}
                <div class="col-sm-4">
                    Father Name:<input type="text" name="father_name" id="id_father_name" required maxlength="50"
                        value="{{ student.father_name }}" />
                </div>
            </div>

            <div class="form-group row">
                <br>
                {% comment %} <label class="col-sm-2 col-form-label">Mother Name:</label>   {% endcomment %}
                <div class="col-sm-4">
                    Mother Name:<input type="text" name="mother_name" id="id_mother_name" required maxlength="50"
                        value="{{ student.mother_name }}" />
                </div>
            </div>

            <div class="form-group row">
                <br>
                <label class="col-sm-2 col-form-label"><br>Address:</label>
                <div class="col-sm-4">
                    <input type="text" name="address" id="id_address" style="width: 301.600px; height: 152px;" required maxlength="500"
                        value="{{ student.address }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="button button4" style=" background:#0040FF; color:black;">Update</button> 
                </div>
            </div>
        </div>
    </form>
</body>

</html>

Django/schoolapp/students/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/> 
    <style>
      .button {
            border: none;
            padding: 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            }
        .button4 {border-radius: 12px;}
    </style> 
</head>  
<body>
<form align="center" method="POST" class="post-form" action="/">  
        {% csrf_token %}  
    <div class="container" style="background:lightgrey; height:100%;">  
    <br>  
        <div class="form-group row">  
          <label class="col-sm-1 col-form-label"></label>  
          <div class="col-sm-4">  
          <h3>Enter Details</h3>  
          </div>  
        </div>  

        <div class="form-group row">  
          <br>
          {% comment %} <label class="col-sm-2 col-form-label">First Name:</label>   {% endcomment %}
          <div class="col-sm-4">  
            First Name:{{ form.first_name }}  
          </div>  
        </div>

        <div class="form-group row">
          <br>  
          {% comment %} <label class="col-sm-2 col-form-label">Last Name:</label>   {% endcomment %}
          <div class="col-sm-4">  
            Last Name:{{ form.last_name }}  
          </div>  
        </div>

        <div class="form-group row">  
          <br>
          {% comment %} <label class="col-sm-2 col-form-label">Age:</label>   {% endcomment %}
          <div class="col-sm-4">  
            Age:{{ form.age }}  
          </div>  
        </div>

        <div class="form-group row">  
          <br>
          {% comment %} <label class="col-sm-2 col-form-label">Gender:</label>   {% endcomment %}
          <div class="col-sm-4">  
            Gender:{{ form.gender }}  
          </div>  
        </div>

        <div class="form-group row">  
          <br>
          {% comment %} <label class="col-sm-2 col-form-label">Roll No:</label>   {% endcomment %}
          <div class="col-sm-4">  
            Roll No:{{ form.roll_no }}  
          </div>  
        </div>

        <div class="form-group row">  
          <br>
          {% comment %} <label class="col-sm-2 col-form-label">Father Name:</label>   {% endcomment %}
          <div class="col-sm-4">  
            Father Name:{{ form.father_name }}  
          </div>  
        </div>

        <div class="form-group row">  
          <br>
          {% comment %} <label class="col-sm-2 col-form-label">Mother Name:</label>   {% endcomment %}
          <div class="col-sm-4">  
            Mother Name:{{ form.mother_name }}  
          </div>  
        </div>

        <div class="form-group row">  
          <br>
          <label class="col-sm-2 col-form-label"><br>Address:</label>  
          <div class="col-sm-4">  
            {{ form.address }}  
          </div>  
        </div>

        <div class="form-group row">  
          <br>
          <label class="col-sm-1 col-form-label"></label>  
          <div class="col-sm-4">  
          <button type="submit" class="button button4" style=" background:#0040FF; color:black;">Submit</button>  
          </div>  
        </div>  
    </div>  
</form>  
</body>  
</html>  

Django/schoolapp/students/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Student Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <style>
        table, th, td{
            border: solid black;
            border-collapse: collapse;
        }
        a, u {
            text-decoration: none;
        }
        a:link {
        color: black;
        }
        a:visited {
        color: black;
        }
        a:hover {
        color: black;
        }
        a:active {
        color: black;
        }
        .button {
            border: none;
            color: black;
            padding: 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            }
        .button4 {border-radius: 12px;}
    </style>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>
        <th>Roll No</th>
        {% comment %} <th>First Name</th>  
        <th>Last Name</th>   {% endcomment %}
        <th>Student Name</th>
        <th>Age</th>
        {% comment %} <th>Date of Birth</th>   {% endcomment %}
        <th>Gender</th>  
        <th>Father Name</th>
        <th>Mother Name</th>  
        <th>Address</th>
        <th>Date of Take Admission</th>
        <th>Last Modified in Form</th>
    </tr>  
    </thead>  
    <tbody>  
{% for student in showdata %}  
    <tr>
        <td>{{ student.roll_no }}</td>  
        <td>{{ student.first_name }} {{ student.last_name }}</td>  
        <td>{{ student.age }}</td>
        {% comment %} <td>{{ student.date_of_birth }}</td>   {% endcomment %}
        <td>{{ student.gender }}</td>
        <td>{{ student.father_name }}</td>
        <td>{{ student.mother_name }}</td>
        <td>{{ student.address }}</td>
        <td>{{ student.registration_date }}</td>
        <td>{{ student.last_modified }}</td> 
        <td>  
            <button class="button button4" style=" background:#00FF57;"><a href="/edit/{{ student.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a></button>  
        </td>    
        <td>
            <button class="button button4" style="background:#FF0000;"><a href="/delete/{{ student.id }}">Delete</a></button>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><button class="button button4" style=" background:#0040FF;"><a href="/" class="btn btn-primary">Add New Record</a></button></center>  
</body>  
</html>

Django/schoolapp/students/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Registration Form</title>
    <style>
        a, u {
                text-decoration: none;
            }
            a:link {
            color: black;
            }
            a:visited {
            color: black;
            }
            a:hover {
            color: black;
            }
            a:active {
            color: black;
            }
            .button {
                border: none;
                color: black;
                padding: 20px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                cursor: pointer;
                }
            .button4 {border-radius: 12px;}
        </style>
</head>
<body>
    <div class="container">
        <h1 align="center"><p class="bg-success">Registration Successful</p></h1> 
        <br><br>
        <button class="button button4" style=" background:#00FF57;"><a href="/show">List of Students take admission</a></button>  
    </div>
</body>
</html>